### ISSUE TITLE
eDNS only searches Common partition / Virtual server created with crd_*

### ISSUE THREAD

**Issue by atdurham** [mdditt2000/kubernetes-1-19#2]
Hey Matt,

I have everything installed (big ip csi, as3, ipam, edns, etc) I can get a virtual server deployed and it tries to make a DNS A record but searches only in Common, when all of my virtual servers are created in ~kubernetes. Also the CIS automatically creates the vitrual servers as "crd_10_10_10_10_80" format, and the F5 DNS throws errors when trying to select pool with "_". Is there a way to make the virtual server name the name of the app, and then also have a way to tell eDNS to look in the kubernetes partition for the virtual server to use as a pool?

Thanks!

Aaron D.

**Comment by mdditt2000** [comment]
Good morning @atdurham You can add an additional object to create a custom virtual name 

https://github.com/F5Networks/k8s-bigip-ctlr/tree/master/docs/_static/config_examples/crd/basic/virtual-server-name

```
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  host: cafe.example.com
  virtualServerAddress: "172.16.3.9"
  virtualServerName: "cafe-virtual-server"
  pools:
  - path: /coffee
    service: svc-2
    servicePort: 80
```
Hopefully is helpful.
